### ISSUE TITLE
Shall we clean SQL queries?

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-instrumentation-doctrine#11]
Queries like

```
\n            SELECT\n              account_id,\n              url,\n              campaign,\n              medium,\n              source,\n              content,\n              term,\n              landing_page,\n              landing_date,\n              created_at\n            FROM some_table\n            WHERE\n              account_id = :account_id\n        
```

have lots of unnecessary space, I believe it can be sanitized and remove spaces but not sure what is the recommended practice.

Any input @adriancole @basvanbeek

**Comment by jorgheymans** [comment]
It might be difficult to trim relevant space without actually parsing the statement.

Take this case statement for example:

```sql
SELECT
first_name, last_name, country,
CASE country
  WHEN '\nUSA\n' THEN 'North America\n'
  WHEN '\nCanada\n' THEN 'North America\n'
  WHEN '\nUK\n' THEN 'Europe\n'
  WHEN '\nFrance\n' THEN 'Europe\n'
  ELSE 'Unknown\n'
END continent
FROM customers
```
Other examples:
```sql
SELECT A || '       ' || B || '    \n' AS "   Concatenated column   " FROM DUAL
```
```sql
SELECT A FROM THETABLE WHERE A = '  Chad does not like using parameter binding  \n'
```

**Comment by jcchavezs** [comment]
Hey @jorgheymans, thanks for the input. I was thinking on using a regex
that only affects whatever is not inside quotes. I think that can be easily
done by saying that everything inside a quote or single quote should be
trimmed. This could be like parsing HTML (fully error  prune) but I believe
it is worth trying. Let’s see if I can come up with a unit test that keeps
such queries.

**Comment by jorgheymans** [comment]
> I was thinking on using a regex that only affects whatever is not inside quotes. I think that can be easily done by saying that everything inside a quote or single quote should be trimmed. 

yes that could work (assuming you mean outside instead of inside). Nested, escaped quotes deserve some attention perhaps

```sql
SELECT "\" \n \"" FROM T
```
Note that i did not realize doctrine is actually a PHP orm, given that probably you can make a lot of assumptions already on the cleanness of the queries you're actually going to get.

**Comment by jcchavezs** [comment]
I also must recognise that the fact that I could find such a thing in
google or stackoverflow made me think it is not a too good idea but there
are plenty of things for parsing HTML so that made me think it is not too
crazy.

lør. 25. mai 2019 kl. 11:46 skrev José Carlos Chávez <jcchavezs@gmail.com>:

**Comment by jcchavezs** [comment]
Well, actually you can pass raw queries and doctrine does not have any
restrictions on that but my idea is that if this work I could implement the
same technique to other sql instrumentations but I also need benchmarks for
the regex. In any case this would be an optional feature.

**Comment by jorgheymans** [comment]
Is the underlying issue that such SQL tag value takes up too much space in the Lens ?

**Comment by jcchavezs** [comment]
Not really. It is more about the fact that we waste space by tagging
queries (that are already long).

**Comment by jorgheymans** [comment]
Would it not be more efficient though to use compression features of the supported storage backends? I'm not an expert in either elastic or cassandra but i can imagine they would have such feature ? 

Curious if we do this in any of the other instrumentation libraries, i.e. modify data before it's reported. @adriancole might chime in here once he finishes his last Nykur ;)

**Comment by codefromthecrypt** [comment]
my curiosity is about which kind of space we are talking about. it is true
some storage backend support column compression and most transports also
include compression.. if it is about visual space in the UI there might be
a formatting library. personally I would prefer to use the time to ask the
ORM to generate nicer SQL ;)

**Comment by jcchavezs** [comment]
Yeah, the space I was talking about is probably the one that floods my obsessive mind because there are stuff that we are storing and we should not. I don't think this is an issue in terms of storage nor bandwith and also I don't see a trivial solution for removing unnecessary stuff from the query so I will close this issue as it is. I think this is not ORM issue either as usually this happens for user direct queries (using the DB abstraction layer) rather than the generated queries by ORMs.
